# frozen_string_literal: true

require 'json'

module RubocopClaude
  class InitWizard
    # Handles installing Claude Code hooks for auto-linting
    class HooksInstaller
      def initialize(wizard)
        @wizard = wizard
      end

      def run
        create_hooks_directory
        create_hook_script
        create_hooks_settings
      end

      private

      def create_hooks_directory
        return if Dir.exist?('.claude/hooks')

        FileUtils.mkdir_p('.claude/hooks')
      end

      def create_hook_script
        dest = '.claude/hooks/ruby-lint.sh'
        File.write(dest, generate_hook_script)
        FileUtils.chmod(0o755, dest)
        @wizard.add_change('Created .claude/hooks/ruby-lint.sh')
        puts "  Created #{dest}"
      end

      def generate_hook_script
        linter_command = if @wizard.hook_linter == 'standardrb'
          'standardrb --fix "$file" 2>&1'
        else
          # Prefer binstub, fall back to bundle exec
          # Use $CLAUDE_PROJECT_DIR to ensure correct path regardless of cwd
          <<~CMD.chomp
            if [[ -x "$CLAUDE_PROJECT_DIR/bin/rubocop" ]]; then
              "$CLAUDE_PROJECT_DIR/bin/rubocop" -a "$file" --format simple 2>&1
            else
              bundle exec rubocop -a "$file" --format simple 2>&1
            fi
          CMD
        end

        <<~SCRIPT
          #!/usr/bin/env bash
          # Claude Code hook: Auto-lint Ruby files after edits
          # Generated by rubocop-claude init --hooks

          set -e

          file="$CLAUDE_EDITED_FILE"
          [[ -z "$file" ]] && exit 0
          [[ "$file" != *.rb ]] && exit 0
          [[ ! -f "$file" ]] && exit 0

          # Autocorrect and report remaining issues
          #{linter_command}
        SCRIPT
      end

      def create_hooks_settings
        dest = '.claude/settings.local.json'
        source = File.join(CLI::TEMPLATES_DIR, 'hooks', 'settings.local.json')

        if File.exist?(dest)
          merge_hooks_settings(dest, source)
        else
          FileUtils.cp(source, dest)
          @wizard.add_change('Created .claude/settings.local.json with hooks')
          puts "  Created #{dest}"
        end
      end

      def merge_hooks_settings(dest, source)
        existing = load_json(dest)
        new_hooks = load_json(source)

        ensure_hooks_structure(existing)
        warn_if_existing_lint_hook(existing['hooks']['PostToolUse'])
        existing['hooks']['PostToolUse'].concat(new_hooks['hooks']['PostToolUse'])

        File.write(dest, JSON.pretty_generate(existing))
        @wizard.add_change('Added Ruby lint hook to .claude/settings.local.json')
        puts "  Updated #{dest}"
      end

      def load_json(path)
        JSON.parse(File.read(path))
      end

      def ensure_hooks_structure(config)
        config['hooks'] ||= {}
        config['hooks']['PostToolUse'] ||= []
      end

      def warn_if_existing_lint_hook(post_tool_use_hooks)
        existing = find_existing_lint_command(post_tool_use_hooks)
        return unless existing

        truncated = (existing.length > 60) ? "#{existing[0, 57]}..." : existing
        puts "  [!] Found existing lint hook: #{truncated}"
        puts '     You may want to remove duplicate hooks from settings.local.json'
      end

      def find_existing_lint_command(post_tool_use_hooks)
        lint_patterns = [/rubocop/i, /standardrb/i, /lint/i, /\.rb/]

        post_tool_use_hooks.each do |hook_config|
          next unless hook_config['matcher'].to_s.match?(/Edit|Write/i)

          (hook_config['hooks'] || []).each do |hook|
            command = hook['command'].to_s
            return command if lint_patterns.any? { |pat| command.match?(pat) }
          end
        end

        nil
      end
    end
  end
end
