---
inherit_gem:
  standard: config/base.yml
inherit_from:
- config/default.yml
plugins:
- rubocop-packaging
- rubocop-performance
- rubocop-rspec
require:
- "./lib/rubocop-claude"
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
  - vendor/**/*
  - tmp/**/*
Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
Layout/LineLength:
  Max: 120
  AllowedPatterns:
  - "^\\s*#"
Metrics/AbcSize:
  Enabled: true
  Max: 17
Metrics/BlockLength:
  Enabled: true
  Max: 25
  Exclude:
  - spec/**/*
  - "*.gemspec"
Metrics/ClassLength:
  Enabled: true
  Max: 150
  CountComments: false
  CountAsOne:
  - array
  - hash
  - heredoc
  - method_call
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 7
Metrics/MethodLength:
  Enabled: true
  Max: 10
  CountComments: false
  CountAsOne:
  - array
  - hash
  - heredoc
  - method_call
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8
Naming/FileName:
  Exclude:
  - lib/rubocop-claude.rb
Naming/PredicatePrefix:
  Exclude:
  - lib/rubocop/cop/claude/**/*
RSpec/ExampleLength:
  Max: 25
RSpec/MultipleExpectations:
  Max: 3
RSpec/NestedGroups:
  Max: 4
Style/Documentation:
  Exclude:
  - spec/**/*
  - lib/rubocop_claude/plugin.rb
  - lib/rubocop_claude/generator.rb
Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

# Integration tests use descriptive strings for describe blocks
RSpec/DescribeClass:
  Exclude:
  - spec/integration/**/*

# Integration test file names match feature, not class
RSpec/SpecFilePathFormat:
  Exclude:
  - spec/integration/**/*

# Intentional emoji in tests and docs that verify/demonstrate emoji detection
Claude/NoFancyUnicode:
  Exclude:
  - spec/integration/plugin_loading_spec.rb
  - spec/rubocop/cop/claude/no_fancy_unicode_spec.rb
  - lib/rubocop/cop/claude/no_fancy_unicode.rb

# Test helpers with self-documenting patterns don't need constants
Claude/MysteryRegex:
  Exclude:
  - spec/**/*
