# frozen_string_literal: true

inherit_gem:
  standard: config/base.yml

inherit_from:
  - config/default.yml

plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

require:
  - ./lib/rubocop-claude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

# =============================================================================
# Gemspec
# =============================================================================

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

# =============================================================================
# Layout
# =============================================================================

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^\s*#'  # Comments can be longer

# =============================================================================
# Metrics
# =============================================================================

Metrics/AbcSize:
  Enabled: true
  Max: 17

Metrics/BlockLength:
  Enabled: true
  Max: 25
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Enabled: true
  Max: 100
  CountComments: false
  CountAsOne: [array, hash, heredoc, method_call]

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 7

Metrics/MethodLength:
  Enabled: true
  Max: 10
  CountComments: false
  CountAsOne: [array, hash, heredoc, method_call]

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8

# =============================================================================
# Naming
# =============================================================================

Naming/FileName:
  Exclude:
    - 'lib/rubocop-claude.rb'  # Standard rubocop plugin convention

Naming/PredicatePrefix:
  Exclude:
    - 'lib/rubocop/cop/claude/**/*'  # Cops use is_* helpers internally

# =============================================================================
# RSpec
# =============================================================================

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4

# =============================================================================
# Style
# =============================================================================

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/rubocop_claude/plugin.rb'
    - 'lib/rubocop_claude/generator.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true
