#!/usr/bin/env bash
# Claude Code hook: Auto-lint Ruby files after edits
# Generated by rubocop-claude init --hooks

set -e

file="$CLAUDE_EDITED_FILE"
[[ -z "$file" ]] && exit 0
[[ "$file" != *.rb ]] && exit 0
[[ ! -f "$file" ]] && exit 0

# Autocorrect and report remaining issues
if command -v standardrb &>/dev/null; then
  standardrb --fix "$file" 2>&1
else
  bundle exec rubocop -A "$file" --format simple 2>&1
fi
